### ISSUE TITLE
as it's a fork, where to open issue on your fork of freeboxos-bash-api

### ISSUE THREAD

**Issue by nbanb** [Sylvain303/ssh-remote_me#1]
Dear Sylvain303

Sorry to open it here, but as it's a fork, I didn't find the way to open an issue it at your fork of freeboxos-bash-api ...

I didn't see your work before I became the main contributor of the original project [freeboxos-bash-api](https://github.com/JrCs/freeboxos-bash-api)

Developping frontend functions in the library (you can see the project I maintien here [fbx-delta-nba_bash_api.sh](https://github.com/nbanb/fbx-delta-nba_bash_api.sh) even if it's had been recently merged with the original project), I also encountering troubles with functions from [JSON.SH](https://github.com/dominictarr/JSON.sh) when freebox API reply a json object that is bigger than 80kb or 100kb

As I need to make the code running in old UNIX systems, I'm not using 'jq' for parsing but I'm dumping all key pairs from the JSON, caching those results and printing the output from cache (see `ls_fs` and nearly all `list_*` functions) and I also develop a  function which is printing json in "pretty json" format: `colorize_output_pretty_json`

In many situations it can be acceptable but sometimes  (for ex: when retrieving a large collection of lanHost objects), it's still too slow. 
From my experiments,  jq-1.5.1 is really faster than jq-1.6 ... 
Which 'jq' are you using  ?
Is the performance gap really interresting? 

Second point, reading your code, I've seen : 
```bash
# ==== ### NOTE ### ====
# The script will WRITE file in its own dir:
# - auth.sh   : [DOESN'T WORK YET] after the authorize process, store SAVED_APP_ID and SAVED_APP_TOKEN
```

You may be interrested by the rewrite of `login_freebox` which publish encrypted credentials to subshell and  my `relogin_freebox` function which made the job automatically for exemple when monitoring a long filesystem task which is longer than the session timeout

Kind regards
nbanba

**Comment by Sylvain303** [comment]
Hello @nbanb,

I didn't used this script since ages. Thanks contacting me.

I moved to jq since this script. And I will never switch back to parsed json again :wink: .

I didn't notice any performance drawback on jq 1.6.  1.6 is the default version on my ubuntu variant. 

> make the code running in old UNIX systems

Is it safe to keep them?

If you absolutely needed to keep "old UNIX systems", well, I suppose you don't have python as well on such OS.

You could:
* (if old os is the same architecture) :  compile a statically linked version of jq, and try to upload it on the destination box
* https://alternativeto.net/software/jq/?platform=linux
* build your own python statically compiled one? Never tried though https://stackoverflow.com/questions/39913847/is-there-a-way-to-compile-a-python-application-into-static-binary 
* virtualize in some way your old OS

What is the benefit for you to keep the old OS?

Hope that helps.

I will open issue on the forked project.
We may be able to chat in French too, as I suppose for using freebox OS you should speak French too. :wink:

**Comment by Sylvain303** [comment]
https://github.com/Sylvain303/freeboxos-bash-api/issues

**Comment by nbanb** [comment]
Dear @Sylvain303 

Thanks for your answer and for reconfiguring the fork repository with 'issue' part.
Mooving contents and switching (in french) to the other issue related to the good project 

I think you can close this issue.
Thanks and king regards
nbanba
